export enum TicketCategory {
  MISSING_PLAN = "MISSING_PLAN",
  INCORRECT_DATA = "INCORRECT_DATA",
  SITE_ERROR = "SITE_ERROR",
  TECH_SUPPORT = "TECH_SUPPORT",
  OPINION = "OPINION",
  SUGGESTION = "SUGGESTION",
  COOPERATION = "COOPERATION",
  OTHER = "OTHER"
}
